# Generated by Django 4.1.7 on 2023-05-14 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0006_alter_issues_assignee_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=256)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "author_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="comment",
                        related_query_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issues_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        related_query_name="comments",
                        to="issues.issues",
                    ),
                ),
            ],
        ),
    ]
