# Generated by Django 4.1.7 on 2023-05-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issues",
            name="id",
        ),
        migrations.AddField(
            model_name="issues",
            name="issues_id",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
