# Generated by Django 4.1.7 on 2023-05-12 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0002_remove_issues_id_issues_issues_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issues",
            name="assignee_user_id",
        ),
        migrations.AddField(
            model_name="issues",
            name="assignee_user_id",
            field=models.ManyToManyField(
                related_name="responsible", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
