# Generated by Django 4.1.7 on 2023-05-13 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0004_remove_issues_assignee_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="assignee_user_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="responsible",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
