# Generated by Django 4.1.7 on 2023-05-14 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0006_alter_contributor_user_id_and_more"),
        ("issues", "0005_alter_issues_assignee_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="assignee_user_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="responsible_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="author_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="issue",
                related_query_name="issues",
                to="project.project",
            ),
        ),
    ]
