# Generated by Django 4.1.7 on 2023-06-18 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0006_alter_contributor_user_id_and_more"),
        ("issues", "0006_alter_issues_assignee_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="assignee_user_id",
            field=models.ForeignKey(
                default=models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="issues_created",
                    to=settings.AUTH_USER_MODEL,
                ),
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="responsible_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="priority",
            field=models.CharField(
                choices=[
                    ("FAIBLE", "FAIBLE"),
                    ("MOYENNE", "MOYENNE"),
                    ("ELEVEE", "ELEVEE"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue",
                related_query_name="issues",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="status",
            field=models.CharField(
                choices=[
                    ("A faire", "A faire"),
                    ("En cours", "En cours"),
                    ("Termine", "Termine"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="tag",
            field=models.CharField(
                choices=[
                    ("BUG", "BUG"),
                    ("AMELIORATION", "AMELIORATION"),
                    ("TACHE", "TACHE"),
                ],
                max_length=20,
            ),
        ),
    ]
