# Generated by Django 4.1.7 on 2023-06-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=256),
        ),
    ]
